### ISSUE TITLE
The problem of code running error

### ISSUE THREAD

**Issue by SwaggyZhang** [fanolabs/0shot-classification#1]
When running ‘main_spin_outlier.py’, _get_anomaly_algorithms()_ in config.py is missing a parameter _k_
```python
def get_anomaly_algorithms(algorithm_key, k, outlier_fraction)
```
This parameter is added when the function was defined, however, it is not filled while running:
```python
algorithm = get_anomaly_algorithms(config_outlier['algorithm_key'][0],
                                       config_outlier['outlier_fraction'])
```

**Comment by floatSDSDS** [comment]
Indeed, we studied the parameter k for SEG but forgot to add it in the zero-shot part.
To fix it, simply change it to
`
    algorithm = get_anomaly_algorithms(
        config_outlier['algorithm_key'][0],
        config_outlier['k'], config_outlier['outlier_fraction'])
`
Thanks for the report.

**Comment by floatSDSDS** [comment]
> When running ‘main_spin_outlier.py’, _get_anomaly_algorithms()_ in config.py is missing a parameter _k_
> 
> ```python
> def get_anomaly_algorithms(algorithm_key, k, outlier_fraction)
> ```
> 
> This parameter is added when the function was defined, however, it is not filled while running:
> 
> ```python
> algorithm = get_anomaly_algorithms(config_outlier['algorithm_key'][0],
>                                        config_outlier['outlier_fraction'])
> ```

Hi, are you there? we have fixed the bugs and please clone the latest version of the code. Thanks

**Comment by SwaggyZhang** [comment]
Hi, thanks for your answer! The bugs were fixed!

**Comment by floatSDSDS** [comment]
> Hi, thanks for your answer! The bugs were fixed!

Actually, what I want to emphasize here is, we have accidentally uploaded some sensitive data in it, so is it possible for you to delete the original version you cloned and update to the latest version?
